model_args:
    model_name: 'mlp_s2s'
    input_size: 60
    hidden_sizes: [768, 640, 512, 640, 640]
    output_size: 60
    learning_rate: 0.001
    num_workers: 0
    epochs: 300
    
data_args:
    batch_size: 32
    train_years: [2016, 2017, 2018, 2019, 2020, 2021]
    val_years: [2022]